version: '3.7'

volumes:
  logs:
    driver: local
  rclone_config:
    driver: local

services:
  frankenphp:
    build: .
    working_dir: /var/www
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    tty: true
    volumes:
      - .:/var/www
      - logs:/var/www/logs
      # Mount the Windows rclone.conf file into the container
      - /c/Users/Guest.02/AppData/Roaming/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro  # Adjust Windows path for Docker
